services:
  postgres:
    image: postgres:15.5
    container_name: postgres_docker_15_5
    environment:
      POSTGRES_DB: "resume"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql